## These are supported funding model platforms

github: glistenstar
patreon: danil S
open_collective: 
ko_fi: 
tidelift: 
liberapay: 
issuehunt: 
otechie: 
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
