## These are supported funding model platforms

github: glistenstar
patreon: danil S
open_collective: glistenstar
ko_fi: danilshelikhov
tidelift: react.js
liberapay: danilshelikhov
issuehunt: glistenstar
otechie: ROY
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
