## These are supported funding model platforms

github: glistenstar
patreon: Marko
open_collective: Marko
ko_fi: Marko
tidelift: Marko
liberapay: Marko
issuehunt: Marko
otechie: Marko
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
