## These are supported funding model platforms

github: GlistenSTAR
patreon: GlistenSTAR
open_collective: GlistenSTAR
ko_fi: GlistenSTAR
tidelift: GlistenSTAR
liberapay: GlistenSTAR
issuehunt: GlistenSTAR
otechie: GlistenSTAR
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
