module.exports = {
  mongoURI: "mongodb://localhost/Chiqui",//your cloud mongodb uri write here  
    secretOrKey: "PBFPVYFBQXZTYFPBFEQJHDXXQVAPTPQJKTOYQWIPBVWLXTOXBTFXQ!^#WAXBVCXQWAXFQJVWLEQNTOZQGGQLFXQWAKVWLXQWAEBIPBFXF!QVXGTVJVWLBTPQWAEBFPBFHCVLXBQUFEVWLXGDP"
  };