module.exports = {
  mongoURI: "mongodb://localhost/AutoLab",//your cloud mongodb uri write here  
    secretOrKey: "PBFPVYFBQXZTYFPBFEQJHDXXQVAPTPQJKTOYQWIPBVWLXTOXBTFXQ!^#WAXBVCXQWAXFQJVWLEQNTOZQGGQLFXQWAKVWLXQWAEBIPBFXF!QVXGTVJVWLBTPQWAEBFPBFHCVLXBQUFEVWLXGDP"
  };